# Generated by Django 3.1.4 on 2021-01-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicinerecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='mrp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicines',
            name='pr',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicines',
            name='rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
